version: '3.4'
services:
  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter
    hostname: jupyter
    ports:
      - 8888:8888
    user: '0'
    restart: always
    volumes:
      - ./az_en_jupyter_mappam:/home/jovyan/work